#!/bin/bash

source $PODGL/lib/fsh.cfg.sh
PATH=$PATH:$PODGL/run:$PODGL/bin

move $1 $2
printf "┌"
for i in $(seq 1 $4); do
   printf "─"
done

printf  "┐"
move $(("$1" + 1)) $2

for i in $(seq 1 $3); do
  printf "│"
  move $(("$1" + i)) $2
done


printf "└"
for i in $(seq 1 $4); do
  printf "─"
done
printf "┘"

move $(("$1" + 1)) $(("$2" + "$4" +1))

for i in $(seq 1 "$3"); do
  printf "│"
  move $(("$1" + i)) $(( "$2" + "$4" + 1))

done

printf "\n"
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     │                            │                                               
#     └────────────────────────────┘
