#!/bin/sh
# Create binary ts3d.exe using MinGW. See windows.md.

if [ -z "$CC" ]; then
	CC=x86_64-w64-mingw32-gcc
	export CC
fi
if [ -z "$PDCURSES_DIR" ]; then
	echo >&2 'Set the PDCURSES_DIR environment variable to the root' \
		'directory of PDCurses. Aborting.'
	exit 1
fi

libcurses="$PDCURSES_DIR/wincon/pdcurses.a"

if ! [ -f "$libcurses" ]; then
	echo >&2 "Build $libcurses before running this script. Aborting."
	exit 1
fi

exec make exe="${exe:-ts3d.exe}" \
	CFLAGS="-I$PDCURSES_DIR ${CFLAGS:-}" \
	linkage="${linkage:-} -lm $libcurses" \
	"$@"
