#!/bin/sh -e

ts3d_dir="$PWD"
if ! [ -f ts3d.exe ]; then
	echo >&2 'ts3d.exe must exist to make ts3d.zip'
	exit 1
fi
dir="$PWD/.zip-windows"
rm -rf "$dir"
mkdir "$dir"
out() { rm -rf "$dir"; exit "${1-1}"; }
cd "$dir" || out
mkdir ts3d || out
cp -r "$ts3d_dir/ts3d.exe" "$ts3d_dir/data" ts3d/ || out
cp "$ts3d_dir/LICENSE" ts3d/data/ || out
zip -r ts3d.zip ts3d/ts3d.exe || out
zip -r ts3d.zip ts3d/data || out
cat > ts3d/install.bat <<'EOF'
XCOPY data\ "%AppData%\ts3d\data\" /E /y
EOF
zip -r ts3d.zip ts3d/install.bat
mv ts3d.zip "$ts3d_dir/" || out
cd .. || out
out 0
