#!/bin/bash

source $PODGL/lib/fsh.cfg.sh

printf "${red}CPU$yellow Heater                           (${green}lset$white TARGET ${cyan}cpu/logic)$white\n"
printf "${red}CPU$yellow Fork Bomber                      (${green}lset$white TARGET ${cyan}cpu/fork)$white\n"
printf "${red}DISK$yellow Empty Files Bomber              (${green}lset$white TARGET ${cyan}disk)\n"
printf "${red}MEMORY$yellow Use 100%% Of Memory            (${green}lset$white TARGET ${cyan}memory/heap)\n"
printf "${red}MEMORY$yellow Unlimited Stack Frame Builder (${green}lset$white TARGET ${cyan}memory/stack)$white\n"
echo
cout "Make sure to execute 'use bomb' before executing 'build' command\n"
