#!/bin/bash
cd $PODGL
echo
printf "\033[1;97m ---- This Tool Is Coded By Mahmoud Osman (MLT)----\n"

# Warning, Do not changes this file's data,

black="\033[0;30m"        # Black
red="\033[0;91m"          # Red
green="\033[0;32m"        # Green
yellow="\033[0;93m"       # Yellow
blue="\033[1;34m"         # Blue
purple="\033[0;95m"       # Purple
cyan="\033[0;36m"         # Cyan
white="\033[0;97m"

printf $yellow

z="
";bz='43 A';Xz=' May';gz='e (C';Hz='t'\''s ';Rz='y !\';Fz='l wi';Kz='s Co';Nz='ahmo';Uz='ed a';Lz='ded ';az=':51:';Bz='tf "';Qz=' Onl';Yz=' 202';Mz='By M';Wz='d 19';Sz='nPub';Vz='t We';Az='prin';Cz='(c) ';Ez=' Too';dz='T Re';cz='M ED';Tz='lish';Dz='This';Pz='sman';Zz='1 06';hz=')\n"';fz='t th';Jz='Tool';Gz='th i';Oz='ud O';ez='spec';Iz='Sub-';                                                       
eval "$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$Kz$Lz$Mz$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$az$bz$cz$dz$ez$fz$gz$hz"
z="
";Bz=' ---';Jz='slee';Rz='dule';Qz='n Mo';Sz='s...';Nz='ding';Iz='y...';Mz=' Loa';Fz=' Thi';Kz='p 0.';Hz='Read';Pz='lt-i';Oz=' Bui';Gz='ngs ';Dz=' Get';Ez='ting';Lz='3';Az='echo';Cz='----';                                                   
eval "$Az$Bz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$Cz$z$Az$z$Az$Dz$Ez$Fz$Gz$Hz$Iz$z$Jz$Kz$Lz$z$Az$Mz$Nz$Oz$Pz$Qz$Rz$Sz$z$Jz$Kz$Lz"
echo

#G++ Manual compile

source $PODGL/lib/fsh.cfg.sh

printf $white"[+] Welcome $red`whoami`$white To The Digle Installer at (`date`)\n"
sleep 1
printf "$green[*]$yellow Installing Required Packages... It May take a lot of time $green(10 Min Maximum)$white\n"

printf "\nProgress: 0%% \r"
apt install xterm -y    &> /dev/null
printf "Progress: 14%% \r"
apt install clang gcc g++ -y    &> /dev/null
printf "Progress: 32%% \r"
apt install objdump -y &> /dev/null
printf "Progress: 47%% \r"
apt install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 -y &> /dev/null
apt install netcat -y &> /dev/null
printf "Progress: 49%% \r"
apt install tree -y  &> /dev/null
printf "Progress: 61%% \r"
apt install libncurses-dev -y &> /dev/null
printf "Progress: 74%% \r"
apt install python3 -y &> /dev/null
printf "Progress: 93%% \r"
apt install python3-pip morse espeak -y &> /dev/null
printf "Progress: 100%% ${green}Done\n\n"
sleep 1
cout "Installing Requirements from 're.d' Please Be Patient.."
pip3 install -r $PODGL/media/re.d/requirements.txt &> /dev/null

cout "${GREEN}Packages${WHITE} Installed, Preparing To Start Compilation Please Wait...\n"
sleep 3
cout "${GREEN}Starting Platform Specified ${RED}Bombs${WHITE} And ${RED}Malware ${GREEN}Auto-Compilation...... $GREEN (For Linux Executables (ELF) Only)\n"

g++ $PODGL/sys/bomb/linux/cpu/bomb.cpp -o $PODGL/sys/bomb/linux/cpu/a.exe
g++ $PODGL/sys/bomb/linux/memory/bomb.cpp -o $PODGL/sys/bomb/linux/memory/a.exe
g++ $PODGL/sys/bomb/linux/disk/bomb.cpp -o $PODGL/sys/bomb/linux/disk/a.exe

cout "${GREEN} Malwares & Bombs Compilation Finished.!${WHITE}"

cout Compiling Sources from sbin/....

for sources in $(ls $PODGL/sbin);do
    g++ $PODGL/sbin/$sources -o $(echo $PODGL/bin/$sources | sed s/".cpp"/""/g) -fpermissive -lncurses -lpthread &> /dev/null
done

cby "Compilation Phase Finished Successfully.!"
sleep 1
cout "Starting DB-Devices Phase Compilation...!"



### DB Section
cd $PODGL/dev/dev3
(echo "yes" | make install) &>/dev/null
mv ts3d ../../bin/fps-shooter &> /dev/null
cd - &> /dev/null
### DB End



printf "export CCWD=\$PWD\ncd $PODGL\n$PODGL/zstart.sh \$@" > $PREFIX/bin/digle && chmod 755 $PREFIX/bin/digle
printf "$PODGL/bin/\n$PODGL/run/" > etc/PATH.dgl

chmod +x etc/init.d/*
chmod +x etc/rc.local
chmod +x run/*
chmod +x bin/*
chmod +x dev/*

printf "\nSetup Finished Successfully, If you're using this for the first time, type 'usage' to start.!\n"
sleep 1
